### ISSUE TITLE
NLog 5.x support - when will it be released?

### ISSUE THREAD

**Issue by hallgeir-osterbo-ac** [launchdarkly/dotnet-logging-adapter-nlog#3]
NLog 5.0 was released 16th of May 2022. However, LaunchDarkly.Logging.NLog still only supports NLog < 5.0.

Is there a plan to support 5.x in the near future? Currently, this is the only dependency we have that are blocking us from upgrading NLog.

**Comment by davew9999** [comment]
Also interested in this. Is this package still in support?

**Comment by kinyoklion** [comment]
Released in 1.1.0.
